name: clang-format Check

env:
  INCLUDE_REGEX: ^.*\.((((c|C)(c|pp|xx|\+\+)?$)|((h|H)h?(pp|xx|\+\+)?$))|(inl|ino|pde|proto|cu))$

on:
  push:
    paths:
      - '**.ino'
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - '**.c'
      - '**.inl'
    pull_request:

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          #- check: './'    # path to include
          #  exclude: ''    # path to exclude
           - check: 'src'
          #   exclude: '(Fonts)' # Exclude file paths containing "Fonts"
          # - check: 'examples'
          #   exclude: ''
    steps:
    - uses: actions/checkout@v3.1.0
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '13'
        check-path: ${{ matrix.path['check'] }}
        exclude-regex: ${{ matrix.path['exclude'] }}
        include-regex: ${{ env.INCLUDE_REGEX }}
